# Site settings
title: ColemanCDA
email: alseycmiller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Swift development blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://colemancda.github.io" # the base hostname & protocol for your site
twitter_username: colemancda
github_username:  colemancda

# Build settings
markdown: kramdown
